development: &defaults
  adapter: postgresql
  encoding: utf8
  database: <%= Rails.application.secrets.DB_DATABASE %>
  username: <%= Rails.application.secrets.DB_USERNAME %>
  password: <%= Rails.application.secrets.DB_PASSWORD %>
  host: <%= Rails.application.secrets.DB_HOST %>
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: <%= Rails.application.secrets.DB_DATABASE %>
  username: <%= Rails.application.secrets.DB_USERNAME %>
  password: <%= Rails.application.secrets.DB_PASSWORD %>
  host: <%= Rails.application.secrets.DB_HOST %>
  pool: 5
  timeout: 5000

docker:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: kr_development
  # Rails.application.secrets. >> ENV.fetch('')
  host: <%= Rails.application.secrets.DATABASE_HOST %>
  port: <%= Rails.application.secrets.DATABASE_PORT %>
  username: <%= Rails.application.secrets.DATABASE_USERNAME %>
  password: <%= Rails.application.secrets.DATABASE_PASSWORD %>

test:
  <<: *defaults
