require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("jquery-ui")
require("packs/char")
require("packs/gear")
require("packs/calc")
require("packs/search")
require("packs/jquery.easy-autocomplete.js")

console.log('Webpacker loaded')
