require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("jquery-ui")
require("packs/gear")
require("packs/calc")
require("packs/stat")
require("packs/link")

console.log('Webpacker loaded')
