name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: 3.0.x

    steps:
      - uses: actions/checkout@v2

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.3
      # - name: Github Release
      #   uses: elgohr/Github-Release-Action@v3.1
